# Generated by Django 3.2.16 on 2022-10-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0007_alter_results_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query',
        ),
        migrations.RemoveField(
            model_name='results',
            name='json',
        ),
        migrations.AddField(
            model_name='query',
            name='tweets',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='urls',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='users',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='containter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sent.query'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='key',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='value',
            field=models.CharField(db_index=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
