# Generated by Django 3.2.16 on 2022-10-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0008_auto_20221029_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
