# Generated by Django 3.2.16 on 2022-11-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0011_auto_20221029_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query',
        ),
    ]
