# Generated by Django 3.2.16 on 2022-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sent', '0012_remove_query_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='container',
        ),
        migrations.AddField(
            model_name='results',
            name='query',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
